// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkoED3fZD3rtHLue4DIgGb2CQbSddx5YM',
    appId: '1:503441830389:web:76987a399e8a8f1780f0bc',
    messagingSenderId: '503441830389',
    projectId: 'doingbusinessbygrantthornton',
    authDomain: 'doingbusinessbygrantthornton.firebaseapp.com',
    storageBucket: 'doingbusinessbygrantthornton.appspot.com',
    measurementId: 'G-XCPLS9EDS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-Z93bhMVu9GSzHbKGYgoQKRGjdanJw0',
    appId: '1:503441830389:android:6f27a2e50f8feb8780f0bc',
    messagingSenderId: '503441830389',
    projectId: 'doingbusinessbygrantthornton',
    storageBucket: 'doingbusinessbygrantthornton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgNw8YVApdRKUJZM70wpVgexdNNTtIpuE',
    appId: '1:503441830389:ios:763ca28ea65e6fd380f0bc',
    messagingSenderId: '503441830389',
    projectId: 'doingbusinessbygrantthornton',
    storageBucket: 'doingbusinessbygrantthornton.appspot.com',
    iosBundleId: 'com.example.doingbusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgNw8YVApdRKUJZM70wpVgexdNNTtIpuE',
    appId: '1:503441830389:ios:763ca28ea65e6fd380f0bc',
    messagingSenderId: '503441830389',
    projectId: 'doingbusinessbygrantthornton',
    storageBucket: 'doingbusinessbygrantthornton.appspot.com',
    iosBundleId: 'com.example.doingbusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkoED3fZD3rtHLue4DIgGb2CQbSddx5YM',
    appId: '1:503441830389:web:6fdba17e360dc20b80f0bc',
    messagingSenderId: '503441830389',
    projectId: 'doingbusinessbygrantthornton',
    authDomain: 'doingbusinessbygrantthornton.firebaseapp.com',
    storageBucket: 'doingbusinessbygrantthornton.appspot.com',
    measurementId: 'G-614Q8GKL37',
  );
}
